name: Docker Build and Push

on:
  push:
    branches:
      - main  # Déclenche le pipeline à chaque push sur la branche principale

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Checkout du code
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Connexion à DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # Étape 3 : Construire l'image Docker
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/simple-http-server:latest .

      # Étape 4 : Tagger l'image avec la version 
      - name: Tag Docker image
        run: |
          docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/simple-http-server:latest ${{ secrets.DOCKER_HUB_USERNAME }}/simple-http-server:v1.0

      # Étape 5 : Pousser l'image vers DockerHub
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/simple-http-server:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/simple-http-server:v1.0